include:
  - path: 
      - postgres.yml

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./cmd/app/Dockerfile
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-moddingway}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DEBUG: ${DEBUG:-false}
      GUILD_ID: ${GUILD_ID}
      MOD_LOGGING_CHANNEL_ID: ${MOD_LOGGING_CHANNEL_ID}
  worker:
    container_name: worker
    build:
      context: .
      dockerfile: ./cmd/worker/Dockerfile
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-moddingway}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DEBUG: ${DEBUG:-false}
      GUILD_ID: ${GUILD_ID}
      MOD_LOGGING_CHANNEL_ID: ${MOD_LOGGING_CHANNEL_ID}

  python-app:
    container_name: pythonBot
    build:
      context: .
      dockerfile: ./src/Dockerfile
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-moddingway}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      GUILD_ID: ${GUILD_ID}
      MOD_LOGGING_CHANNEL_ID: ${MOD_LOGGING_CHANNEL_ID}
    depends_on:
      - postgres_local
